### ISSUE TITLE
stickers cannot be sent

### ISSUE THREAD

**Issue by theandychung** [BobbyWibowo/Magane#1]
I can add the stickers from line store by using the `maganeAppendPack` command, but I can't send any of those to discord.

**Comment by theandychung** [comment]
Thank you for the reply. I am using BetterDiscord plugin downloaded from here:

> BetterDiscord
> Plugin: https://blog.fiery.me/Magane/magane.plugin.js.

I did relaunch and tried several times, but nothing works. I can send stickers using the original Magane js by Pitu, but I can't send any sticker when using this repo's js.

**Comment by BobbyWibowo** [comment]
That's very odd. Any errors in console right after you click on any stickers to send?

**Comment by theandychung** [comment]
No response. If I tried to send any sticker again it would always say the plugin is on cooldown.

**Comment by BobbyWibowo** [comment]
This fork makes use of toasts from BetterDiscord's API or Zere's Library, for a better user experience. It seems I screwed up something in the checks, in which it'd just fail if either did not exist or simply broke down. https://github.com/BobbyWibowo/Magane/commit/3cf1fc4bfae45c93560c1ba7c2b44915ff0c20d4 should have this fixed, with niche console logging as fallback.
